use super::{AddressFlags, Interface, InterfaceAddress, InterfaceFlags};
use netlink_packet_core::{NetlinkHeader, NetlinkMessage, NetlinkPayload, NLM_F_DUMP, NLM_F_REQUEST};
use netlink_packet_route::{
    address::{AddressAttribute, AddressFlags as NetlinkAddressFlags, AddressMessage},
    link::{LinkAttribute, LinkFlags, LinkMessage},
    RouteNetlinkMessage,
};
use netlink_sys::{protocols::NETLINK_ROUTE, Socket, SocketAddr};
use std::collections::HashMap;
use std::io;
use std::net::IpAddr;

pub fn get_interfaces() -> io::Result<Vec<Interface>> {
    let mut socket = Socket::new(NETLINK_ROUTE)?;
    socket.bind_auto()?;
    socket.connect(&SocketAddr::new(0, 0))?;
    let links = dump_links(&socket)?;
    dump_addresses(&socket, &links)
}

fn send_dump(socket: &Socket, msg: RouteNetlinkMessage) -> io::Result<()> {
    let mut header = NetlinkHeader::default();
    header.flags = NLM_F_DUMP | NLM_F_REQUEST;
    let mut packet = NetlinkMessage::new(header, NetlinkPayload::InnerMessage(msg));
    packet.finalize();
    let mut buf = vec![0u8; packet.header.length as usize];
    packet.serialize(&mut buf[..]);
    socket.send(&buf, 0)?;
    Ok(())
}

fn recv_dump(socket: &Socket) -> io::Result<Vec<RouteNetlinkMessage>> {
    let mut messages = Vec::new();
    loop {
        let (data, _) = socket.recv_from_full()?;
        let mut offset = 0;
        while offset < data.len() {
            let msg = NetlinkMessage::<RouteNetlinkMessage>::deserialize(&data[offset..])
                .map_err(io::Error::other)?;
            let len = msg.header.length as usize;
            match msg.payload {
                NetlinkPayload::Done(_) => return Ok(messages),
                NetlinkPayload::Error(e) if e.code.is_none() => return Ok(messages),
                NetlinkPayload::Error(e) => {
                    return Err(io::Error::other(format!("netlink error: {e:?}")));
                }
                NetlinkPayload::InnerMessage(m) => messages.push(m),
                _ => {}
            }
            if len == 0 {
                break;
            }
            offset += len;
        }
    }
}

fn dump_links(socket: &Socket) -> io::Result<HashMap<u32, (String, InterfaceFlags)>> {
    send_dump(socket, RouteNetlinkMessage::GetLink(LinkMessage::default()))?;
    let mut links = HashMap::new();
    for msg in recv_dump(socket)? {
        if let RouteNetlinkMessage::NewLink(m) = msg {
            let Some(name) = m.attributes.into_iter().find_map(|a| {
                if let LinkAttribute::IfName(n) = a { Some(n) } else { None }
            }) else {
                continue;
            };
            let mut flags = InterfaceFlags::empty();
            if m.header.flags.contains(LinkFlags::Up) && m.header.flags.contains(LinkFlags::LowerUp) {
                flags = flags.with(InterfaceFlags::UP);
            }
            if m.header.flags.contains(LinkFlags::Loopback) {
                flags = flags.with(InterfaceFlags::LOOPBACK);
            }
            links.insert(m.header.index, (name, flags));
        }
    }
    Ok(links)
}

fn dump_addresses(
    socket: &Socket,
    links: &HashMap<u32, (String, InterfaceFlags)>,
) -> io::Result<Vec<Interface>> {
    // Build one Interface per link in index order so the output is deterministic.
    let mut by_index: HashMap<u32, usize> = HashMap::new();
    let mut interfaces: Vec<Interface> = {
        let mut sorted: Vec<(&u32, &(String, InterfaceFlags))> = links.iter().collect();
        sorted.sort_by_key(|(idx, _)| *idx);
        sorted
            .into_iter()
            .enumerate()
            .map(|(pos, (&idx, (name, flags)))| {
                by_index.insert(idx, pos);
                Interface { name: name.clone(), flags: *flags, addresses: Vec::new() }
            })
            .collect()
    };

    send_dump(socket, RouteNetlinkMessage::GetAddress(AddressMessage::default()))?;
    for msg in recv_dump(socket)? {
        if let RouteNetlinkMessage::NewAddress(m) = msg {
            let Some(&pos) = by_index.get(&m.header.index) else {
                continue;
            };
            let mut address: Option<IpAddr> = None;
            let mut netlink_flags = NetlinkAddressFlags::empty();
            for attr in m.attributes {
                match attr {
                    AddressAttribute::Address(ip) => address = Some(ip),
                    // IFA_FLAGS attr overrides the 8-bit header field with the full 32-bit value.
                    AddressAttribute::Flags(f) => netlink_flags = f,
                    _ => {}
                }
            }
            let mut addr_flags = AddressFlags::empty();
            // IFA_F_SECONDARY == IFA_F_TEMPORARY (0x01). For IPv6, this bit means the
            // address was generated by privacy extensions (RFC 4941) and should not be
            // used as the source for inbound-capable DNS records.
            if netlink_flags.contains(NetlinkAddressFlags::Secondary)
                && matches!(address, Some(IpAddr::V6(_)))
            {
                addr_flags = addr_flags.with(AddressFlags::TEMPORARY);
            }
            if netlink_flags.contains(NetlinkAddressFlags::Deprecated)
                && matches!(address, Some(IpAddr::V6(_)))
            {
                addr_flags = addr_flags.with(AddressFlags::DEPRECATED);
            }
            if let Some(addr) = address {
                interfaces[pos].addresses.push(InterfaceAddress { address: addr, flags: addr_flags });
            }
        }
    }
    interfaces.retain(|i| !i.addresses.is_empty());
    Ok(interfaces)
}

