name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Rustfmt
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  test-native:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: cargo test
      - name: Test (No Features)
        run: cargo test --no-default-features
      - name: Test (All Features)
        run: cargo test --all-features
  test-cross:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - riscv64gc-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Cross
        run: cargo install cross
      - name: Test
        run: cross test --target ${{ matrix.target }}
      - name: Test (No Features)
        run: cross test --target ${{ matrix.target }} --no-default-features
      - name: Test (All Features)
        run: cross test --target ${{ matrix.target }} --all-features
