#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
    [ -d "/etc/cf-ddns" ] || mkdir -p /etc/cf-ddns

    procd_open_instance
    procd_set_param command /usr/bin/cf-ddns service run
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "/etc/cf-ddns/config.toml"
}
